import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect,useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data,setData] = useState();

  useEffect(() => {
    const url = 'https://exercisedb.p.rapidapi.com/exercises/bodyPart/cardio';

    const options = {
      method: 'GET',
      headers: {
        'X-RapidAPI-Key': '182da900e1mshd23e2dd5ebde7d4p17cd44jsnad17788cd053',
        'X-RapidAPI-Host': 'exercisedb.p.rapidapi.com'
      }
    };
    fetch(url, options)
	    .then(res => res.json())
	    .then(res => {
        console.log(res)
        setData(res)
      })
	    .catch(err => {
        console.error('error:' + err)
      });

  },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {
          data && data.map((d)=>{
            return(
              <div key={d.id}>
                <h2>{d.name}</h2>
                <p>{d.gifUrl}</p>
                <Image 
                    src={d.gifUrl} 
                    width={150} 
                    height={150} 
                    alt={d.name}>
                </Image>
              </div>
            )
          })
        }
      </main>
    </>
  )
}
