import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect,useState } from 'react'
import { excersiceOptions,fetchData } from '@/utils/fetchData'


export default function Home() {    
    const url = 'https://exercisedb.p.rapidapi.com/exercises';
    const workout = [ "3/4 sit-up",
    "air bike",
    "all fours squad stretch",
    "alternate heel touchers",
    "ankle circles",
]
    const [data, setData] = useState([])

    const handleSearch = async () => {
        if (workout){
            const exercisesData = await fetchData(url,excersiceOptions)
            console.log(exercisesData)
            const searchedExercise = exercisesData.filter( e => workout.includes(e.name))
                // console.log(s)
                
            console.log(searchedExercise);
       
        
        setData(searchedExercise);
        }
    }
    
 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={handleSearch}>
            search
        </button>
        {
          data && data.map((d)=>{
            return(
              <div key={d.id}>
                <h2>{d.name}</h2>
                <p>{d.gifUrl}</p>
                <Image 
                    src={d.gifUrl} 
                    width={150} 
                    height={150} 
                    alt={d.name}>
                </Image>
              </div>
            )
          })
        }
      </main>
    </>
  )
}
